### PR TITLE
switch to alienfile + Alien::Build

### PR DESCRIPTION
**Pull request by plicease**
This offers some improvements over the existing version of Alien::OpenSSL.

 - Ability to download openssl source via https using curl or wget
   - Falls back on FTP in that does not work
   - User can turn off FTP fetch for environments that require that
 - Add Test::Alien tests to ensure that Alien works with XS (and optionally FFI).
 - Fewer dependencies (no need for Module::Build or A::B::MB)
 - Works with Visual C++ Perl on Windows

### CODE REVIEW

**Comment by 0xxon** [comment]
Hi. Thanks a lot for this, this is pretty great :)

Sadly this currently seems to break building old versions of OpenSSL. To be specific, when using ALIEN_INSTALL_TYPE=share and calling

`perl Makefile.PL --version=1.0.2l`
`make`

The build process fails with:

```
[...]
make[2]: Leaving directory '/home/johanna/crypt/alien-openssl/_alien/build_YzNS/openssl-1.0.2l/test'
making install in tools...
make[2]: Entering directory '/home/johanna/crypt/alien-openssl/_alien/build_YzNS/openssl-1.0.2l/tools'
make[2]: Leaving directory '/home/johanna/crypt/alien-openssl/_alien/build_YzNS/openssl-1.0.2l/tools'
installing libcrypto.a
installing libssl.a
installing libcrypto.so.1.0.0
installing libssl.so.1.0.0
make[2]: Entering directory '/home/johanna/sw/lib/perl5/site_perl/5.24.1/x86_64-linux/auto/share/dist/Alien-OpenSSL/lib'
make[3]: Entering directory '/home/johanna/sw/lib/perl5/site_perl/5.24.1/x86_64-linux/auto/share/dist/Alien-OpenSSL/lib'
make[3]: Leaving directory '/home/johanna/sw/lib/perl5/site_perl/5.24.1/x86_64-linux/auto/share/dist/Alien-OpenSSL/lib'
make[3]: Entering directory '/home/johanna/sw/lib/perl5/site_perl/5.24.1/x86_64-linux/auto/share/dist/Alien-OpenSSL/lib'
make[3]: Leaving directory '/home/johanna/sw/lib/perl5/site_perl/5.24.1/x86_64-linux/auto/share/dist/Alien-OpenSSL/lib'
make[2]: Leaving directory '/home/johanna/sw/lib/perl5/site_perl/5.24.1/x86_64-linux/auto/share/dist/Alien-OpenSSL/lib
OpenSSL shared libraries have been installed in:
  /home/johanna/sw/lib/perl5/site_perl/5.24.1/x86_64-linux/auto/share/dist/Alien-OpenSSL

If this directory is not in a standard system path for dynamic/shared
libraries, then you will have problems linking and executing
applications that use OpenSSL libraries UNLESS:

* you link with static (archive) libraries.  If you are truly
  paranoid about security, you should use static libraries.
* you use the GNU libtool code during linking
  (http://www.gnu.org/software/libtool/libtool.html)
* you use pkg-config during linking (this requires that
  PKG_CONFIG_PATH includes the path to the OpenSSL shared
  library directory), and make use of -R or -rpath.
  (http://www.freedesktop.org/software/pkgconfig/)
* you specify the system-wide link path via a command such
  as crle(1) on Solaris systems.
* you add the OpenSSL shared library directory to /etc/ld.so.conf
  and run ldconfig(8) on Linux systems.
* you define the LD_LIBRARY_PATH, LIBPATH, SHLIB_PATH (HP),
  DYLD_LIBRARY_PATH (MacOS X) or PATH (Cygwin and DJGPP)
  environment variable and add the OpenSSL shared library
  directory to it.

One common tool to check the dynamic dependencies of an executable
or dynamic library is ldd(1) on most UNIX systems.

See any operating system documentation and manpages about shared
libraries for your version of UNIX.  The following manpages may be
helpful: ld(1), ld.so(1), ld.so.1(1) [Solaris], dld.sl(1) [HP],
ldd(1), crle(1) [Solaris], pldd(1) [Solaris], ldconfig(8) [Linux],
chatr(1) [HP].
cp libcrypto.pc /home/johanna/sw/lib/perl5/site_perl/5.24.1/x86_64-linux/auto/share/dist/Alien-OpenSSL/lib/pkgconfig
chmod 644 /home/johanna/sw/lib/perl5/site_perl/5.24.1/x86_64-linux/auto/share/dist/Alien-OpenSSL/lib/pkgconfig/libcrypto.pc
cp libssl.pc /home/johanna/sw/lib/perl5/site_perl/5.24.1/x86_64-linux/auto/share/dist/Alien-OpenSSL/lib/pkgconfig
chmod 644 /home/johanna/sw/lib/perl5/site_perl/5.24.1/x86_64-linux/auto/share/dist/Alien-OpenSSL/lib/pkgconfig/libssl.pc
cp openssl.pc /home/johanna/sw/lib/perl5/site_perl/5.24.1/x86_64-linux/auto/share/dist/Alien-OpenSSL/lib/pkgconfig
chmod 644 /home/johanna/sw/lib/perl5/site_perl/5.24.1/x86_64-linux/auto/share/dist/Alien-OpenSSL/lib/pkgconfig/openssl.pc
make[1]: Leaving directory '/home/johanna/crypt/alien-openssl/_alien/build_YzNS/openssl-1.0.2l'
nothing was installed into destdir at /home/johanna/sw/lib/perl5/site_perl/5.24.1/Alien/Build/Plugin/Core/Gather.pm line 70.
Makefile:955: recipe for target '_alien/mm/build' failed
make: *** [_alien/mm/build] Error 2
```

I currently rely on this still working with old versions of OpenSSL and am not quite sure why this breaks with your changes. Could you perhaps fix this :)?

**Comment by plicease** [comment]
I am able to reproduce this.  I will let you know if I figure out a way to fix it.

**Comment by 0xxon** [comment]
Apparently DESTDIR is new for 1.1; for 1.0.x it seems that one has to use INSTALL_PREFIX instead. I can look at it in a few days if you have not fixed it by then :)

**Comment by plicease** [comment]
Yeah I suspected something like that.

**Comment by 0xxon** [comment]
Small update - I have this fixed to work with OpenSSL 1.0 - so you don't have to do anything, I will just add that part when I merge.

However, one small additional question. When using export ALIEN_INSTALL_TYPE=share and just building against OpenSSL 1.1 (so after just calling perl Makefile.PL && make), I get the following test failure on os-x:

```
$ make test
PERL_DL_NONLAZY=1 "/Users/johanna/sw/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-use.t ........ 1/2 # Libs: -L/Users/johanna/crypt/alien-openssl/blib/lib/auto/share/dist/Alien-OpenSSL/lib -lssl -lcrypto
# Cflags: -I/Users/johanna/crypt/alien-openssl/blib/lib/auto/share/dist/Alien-OpenSSL/include
# Install type: share
t/00-use.t ........ ok
t/01-signature.t .. skipped: Set the environment variable TEST_SIGNATURE to enable this test.
t/author-pod.t .... skipped: Author testing disabled
t/ffi.t ........... ok
t/xs.t ............ 1/?
# Failed test 'xs'
# at t/xs.t line 14.
#   DynaLoader failed
#     Can't load 'testalieneh9LR/auto/Test/Alien/XS/Mod0/Mod0.bundle' for module Test::Alien::XS::Mod0: dlopen(testalieneh9LR/auto/Test/Alien/XS/Mod0/Mod0.bundle, 2): Symbol not found: _OpenSSL_version
#   Referenced from: testalieneh9LR/auto/Test/Alien/XS/Mod0/Mod0.bundle
#   Expected in: flat namespace
#  in testalieneh9LR/auto/Test/Alien/XS/Mod0/Mod0.bundle at /Users/johanna/sw/lib/perl5/5.24.1/darwin-2level/DynaLoader.pm line 197.
#  at /Users/johanna/sw/lib/perl5/site_perl/5.24.1/Test/Alien.pm line 422.
# Compilation failed in require at /Users/johanna/sw/lib/perl5/site_perl/5.24.1/Test/Alien.pm line 422.
# BEGIN failed--compilation aborted at /Users/johanna/sw/lib/perl5/site_perl/5.24.1/Test/Alien.pm line 422.
# Seeded srand with seed '20171010' from local date.
t/xs.t ............ Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests

Test Summary Report
-------------------
t/xs.t          (Wstat: 256 Tests: 3 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
Files=5, Tests=8,  1 wallclock secs ( 0.03 usr  0.02 sys +  0.64 cusr  0.12 csys =  0.81 CPU)
Result: FAIL
Failed 1/5 test programs. 1/8 subtests failed.
make: *** [test_dynamic] Error 1
```
Do you have any clue why this happens?

**Comment by plicease** [comment]
Curious, I am not seeing that on my OS X.  Can you try with this commit:

https://github.com/plicease/Alien-OpenSSL/commit/f918ed673c26a912a53ff487f8ad1c45b6fc0adc

and run `prove -bvm t/xs.t` to get the full compiler invocation?

Thanks!

**Comment by 0xxon** [comment]
Sure:

```
$ prove -bvm t/xs.t
t/xs.t ..
# Seeded srand with seed '20171011' from local date.
ok 1 - Alien::OpenSSL responds to: cflags libs dynamic_libs bin_dir
# detect module name Test::Alien::XS::Mod0
# parse xs testaliensBlD4/test.xs => testaliensBlD4/test.c
#
# compile testaliensBlD4/test.c
# cc -I/Users/johanna/sw/lib/perl5/5.24.1/darwin-2level/CORE -I/Users/johanna/crypt/alien-openssl/blib/lib/auto/share/dist/Alien-OpenSSL/include -c -fno-common -DPERL_DARWIN -mmacosx-version-min=10.12 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -I/opt/local/include -DPERL_USE_SAFE_PUTENV -O3 -o testaliensBlD4/test.o testaliensBlD4/test.c
# link testaliensBlD4/test.o
# cc -mmacosx-version-min=10.12 -bundle -undefined dynamic_lookup -L/usr/local/lib -L/opt/local/lib -fstack-protector-strong -o testaliensBlD4/test.bundle testaliensBlD4/test.o -L/Users/johanna/crypt/alien-openssl/blib/lib/auto/share/dist/Alien-OpenSSL/lib -lssl -lcrypto
# created lib testaliensBlD4/test.bundle
ok 2 - xs
dyld: lazy symbol binding failed: Symbol not found: _OpenSSL_version
  Referenced from: testaliensBlD4/auto/Test/Alien/XS/Mod0/Mod0.bundle
  Expected in: flat namespace

dyld: Symbol not found: _OpenSSL_version
  Referenced from: testaliensBlD4/auto/Test/Alien/XS/Mod0/Mod0.bundle
  Expected in: flat namespace

All 2 subtests passed

Test Summary Report
-------------------
t/xs.t (Wstat: 6 Tests: 2 Failed: 0)
  Non-zero wait status: 6
  Parse errors: No plan found in TAP output
Files=1, Tests=2,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.34 cusr  0.10 csys =  0.47 CPU)
Result: FAIL
```

The loader seems to resolve the bundle to the wrong openssl installation (a macports one):
```
$ otool -L testaliensBlD4/auto/Test/Alien/XS/Mod0/Mod0.bundle
testaliensBlD4/auto/Test/Alien/XS/Mod0/Mod0.bundle:
	/opt/local/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/opt/local/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```

**Comment by 0xxon** [comment]
To comment on this again - I assume that the ordering of -L's in the cc call might be the problem. Specifically - the  -L/usr/local/lib -L/opt/local/lib should probably be at the end.

Is there any other way I can help with this?

**Comment by plicease** [comment]
I am going to take a look when I get a chance.  It may be an issue with Test::Alien.

**Comment by plicease** [comment]
I believe I have this fixed in Alien-Build 1.26_01 on its way to CPAN right now.  Can you try it with that version?

**Comment by plicease** [comment]
I added a test directive so that the OpenSSL test suite is run.  This was in the old AB::MB version.

**Comment by 0xxon** [comment]
Yup, this seems to work perfectly now. Will merge and upload a new version to cpan once the new Alien::Build is released.

As a (unimportant) side note - for me the OpenSSL test suite still does not seem to run, even with the test directive. (Doing make followed by make test and make install).

**Comment by plicease** [comment]
Doesn't run for a `share` install?  It shouldn't of course run on a system install.

**Comment by 0xxon** [comment]
Yup, it did not seem to run for a share install for me, even with the added line.

**Comment by plicease** [comment]
Can you send me a copy of the Makefile (either as a gist or to plicease@cpan.org).

**Comment by 0xxon** [comment]
Sure - https://gist.github.com/0xxon/9b7e9cf99ae96b86911661c55faab073

**Comment by plicease** [comment]
If you get a chance and want to try it with 1.27_01 I think I have that fixed here.
https://metacpan.org/release/PLICEASE/Alien-Build-1.27_01
I was able to reproduce myself with an older version of Perl + older version of EUMM so I think we are set.  Production release of AB to follow soonish.

**Comment by plicease** [comment]
fyi- Fixed version of Test::Alien is now on CPAN as part of Alien-Build 1.28.

**Pull request merged**
